#!/usr/bin/env ruby

# frozen_string_literal: true

require "optparse"
require "rspec"

options = {}

OptionParser.new do |opts|
  opts.banner = "Usage: main.rb day [options]"

  opts.on("-h", "--help", "Help") do
    puts opts
    exit
  end

  opts.on("-i", "--input str", "Input String") do |str|
    options[:input] = str
  end

  opts.on("-s", "--split split", "Split on") do |split|
    options[:split_on] = split
  end

  opts.on("-f", "--file filename", "Input Filename") do |f|
    options[:split_on] = "\n" unless options.has_key?(:split_on)
    options[:input] = File.read(f).split(options[:split_on])
  end

  opts.on("-t", "--test", "Run tests") do |test|
    options[:test] = test
  end
end.parse!

if options[:test]
  filename = "./spec/#{ARGV[0]}_spec.rb"
  RSpec::Core::Runner.run([filename], $stderr, $stdout)
else
  filename = "./src/#{ARGV[0]}.rb"
  require_relative filename

  p main(options[:input])
end
